export const rateCardList = [
  {
    id: 1,
    currency: "USD",
    currencyList: [
      {
        id: 1,
        chieldCurrency: "EUR",
        value: 1.386,
      },
      {
        id: 2,
        chieldCurrency: "GBP",
        value: 1.16,
      },
      {
        id: 3,
        chieldCurrency: "NGN",
        value: 1.11,
      },
    ],
  },
  {
    id: 2,
    currency: "EUR",
    currencyList: [
      {
        id: 1,
        chieldCurrency: "NGN",
        value: 925.0,
      },
      {
        id: 2,
        chieldCurrency: "USD",
        value: 786.0,
      },
      {
        id: 3,
        chieldCurrency: "GBP",
        value: 1.0,
      },
    ],
  },
  {
    id: 1,
    currency: "GBR",
    currencyList: [
      {
        id: 1,
        chieldCurrency: "USD",
        value: 0.71534,
      },
      {
        id: 2,
        chieldCurrency: "NGN",
        value: 0.86553,
      },
      {
        id: 3,
        chieldCurrency: "EUR",
        value: 0.7445,
      },
    ],
  },
];

export const users = [
  {
    id: 200,
    name: "Regina Catherine",
    email: "regina@gmail.com",
    type: "Checker",
    active: "In Active",
    created_at: "24 hours ago",
  },
  {
    id: 201,
    name: "Catherine Joy",
    email: "catherine@gmail.com",
    type: "Maker",
    active: "Active",
    created_at: "24 hours ago",
  },

  {
    id: 202,
    name: "Catherine Joy",
    email: "catherine@gmail.com",
    type: "Maker",
    active: "In active",
    created_at: "24 hours ago",
  },
  {
    id: 203,
    name: "Catherine Joy",
    email: "catherine@gmail.com",
    type: "Maker",
    active: "In active",
    created_at: "24 hours ago",
  },
  {
    id: 204,
    name: "Catherine Joy",
    email: "catherine@gmail.com",
    type: "Maker",
    active: "In active",
    created_at: "24 hours ago",
  },
  {
    id: 205,
    name: "Catherine Joy",
    email: "catherine@gmail.com",
    type: "Maker",
    active: "In active",
    created_at: "24 hours ago",
  },
  {
    id: 206,
    name: "Catherine Joy",
    email: "catherine@gmail.com",
    type: "Maker",
    active: "In active",
    created_at: "24 hours ago",
  },
];
export const TradesTableHeader = [
  {
    id: 1,
    title: "Trade Id",
  },
  {
    id: 2,
    title: "Account",
  },
  {
    id: 3,
    title: "Product",
  },
  {
    id: 4,
    title: "Sell Amount",
  },
  {
    id: 5,
    title: "Debit Amount",
  },
  {
    id: 6,
    title: "Ref. Amount",
  },
  {
    id: 7,
    title: "Trade Date",
  },
  {
    id: 8,
    title: "Status",
  },
  {
    id: 9,
    title: "Action",
  },
];
export const TradesTableBody = [
  {
    id: 1,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "pending",
  },
  {
    id: 2,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "approved",
  },
  {
    id: 3,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "approved",
  },
  {
    id: 4,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "rejected",
  },
  {
    id: 1,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "pending",
  },
  {
    id: 2,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "approved",
  },
  {
    id: 3,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "approved",
  },
  {
    id: 4,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "pending",
  },
  {
    id: 1,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "pending",
  },
  {
    id: 2,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "approved",
  },
  {
    id: 3,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "approved",
  },
  {
    id: 4,
    trade_date: "2/4/2017",
    cust_ref: "670471962",
    product: "Funds Transfer Outflow - Dorm Settlement",
    name: "Ishita Kumar",
    number: "5092415259",
    sell: "6508.40",
    sell_currency: "USD",
    debit_currency: "NGN",
    debit: "3594483.74",
    status: "pending",
  },
];

export const statusOptions: any = [
  {
    label: "Pending",
    value: "0",
  },
  {
    label: "Approved",
    value: "1",
  },
  {
    label: "Rejected",
    value: "2",
  },
];

export const setSettleOptions: any = [
  {
    label: "Cash",
    value: 2,
  },
  {
    label: "Nostro",
    value: 1,
  },
];

export const products: any = [
  {
    label: "Google",
    value: "Google",
  },
  {
    label: "Facebook",
    value: "Facebook",
  },
  {
    label: "Apple",
    value: "Apple",
  },
];

export const currency: any = [
  {
    label: "USD",
    value: "USD",
  },
  {
    label: "INR",
    value: "INR",
  },
  {
    label: "EUR",
    value: "EUR",
  },
];
export const direction: any = [
  {
    label: "SELL",
    value: "SELL",
  },
];
export const ProductsTableHeader = [
  {
    id: 2,
    title: "Product Name",
  },
  {
    id: 3,
    title: "Reference Currency",
  },
  {
    id: 4,
    title: "Product Category",
  }, 
  {
    id: 5,
    title: "Book",
  },
  {
    id: 6,
    title: "Action",
  },
];

export const productsList = [
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 2,
    product_name: "PRODUCT NAME",
    ref_ccy: "GBR",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 3,
    product_name: "PRODUCT NAME",
    ref_ccy: "USD",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
  {
    id: 1,
    product_name: "PRODUCT NAME",
    ref_ccy: "REF CCY",
    type: "TYPE",
    book: "BOOK",
    created_at: "24 min ago",
    checked: false,
  },
];
export const product: any = [
  {
    label: "Spot - Allocation - Dorm Settlement",
    value: "Spot - Allocation - Dorm Settlement",
  },
  {
    label: "Spot - Allocation - Nostro Settlement",
    value: "Spot - Allocation - Nostro Settlement",
  },
  {
    label: "Spot - Fund Transfer Outflow - Nostro Settlement",
    value: "Spot - Fund Transfer Outflow - Nostro Settlement",
  },
  {
    label: "Spot - Fund Transfer Outflow - Dorm Settlement",
    value: "Spot - Fund Transfer Outflow - Dorm Settlement",
  },
  {
    label: "Spot - Invisible Remittances - Nostro/Cash settlement",
    value: "Spot - Invisible Remittances - Nostro/Cash settlement",
  },
  {
    label: "Spot - Invisible Remittances - Dorm Settlement",
    value: "Spot - Invisible Remittances - Dorm Settlement",
  },
];

export const option: any = {
  position: "top-right", // Position of the toast
  autoClose: 3000, // Auto-close the toast after 5 seconds (set to false to disable)
  hideProgressBar: false, // Display a progress bar
  closeOnClick: true, // Close the toast when clicked
  pauseOnHover: true, // Pause the timer when hovered
  draggable: true, // Make the toast draggable
};
