"use client";
import { AuthContextProvider } from "@/lib";
import "./globals.css";
//import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";
import { SessionProvider } from "next-auth/react";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

/*export const metadata: Metadata = {
  title: "retail-fx",
  description: "Generated by create next app",
};
*/
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${roboto.className} bg-zinc-50`}>
        <SessionProvider refetchInterval={6000}>
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
